# This is a basic workflow to help you get started with Actions

name: PR test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [push, pull_request]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      
    - name: Line Check
      shell: bash
      run: |
          filelist=`ls ${{ github.workspace }}`
          echo $filelist | while read line ;
          do
            fileline=`cat $line | sed '/^$/d' | wc -l`
            fileline=`echo "${fileline:(-1)}"`
            sum=$(($fileline%2))
            if [ $sum = 0 ]
                  then
                      echo "success"
                  else
                      return `failure()`
              fi
          done
